#+STARTUP: overview
#+STARTUP: latexpreview
#+TITLE: Outline of paper
#+AUTHOR: Sayantan Khan

#+LaTeX_HEADER: \usepackage[extreme]{savetrees}
#+LaTeX_HEADER: \usepackage[utf8]{inputenc}
#+LaTeX_HEADER: \thispagestyle{empty}

* Outline

What should the main theorems/constructions in the paper be?
- The weak convex core, and proof of how it's weak convex.
- Geodesics that spend an appreciable amount of time in the thin part are exponentially rare. Compare this to similar results for measures induced by random walks.
- Equality of lattice point entropy and net point entropy. Can think of this as a very weak version of ABEM, but proven without using dynamics.
- (Optional, might only be in thesis) Application to Patterson-Sullivan theory.
- (Appendix) HHS structure for non-orientable Teichmüller spaces.


* Proof of entropy equality

Need to deal with the two base cases: once punctured torus and a Klein bottle(?). The Teichmüller space in the first case is hyperbolic, so we can use the tail volume estimates. In thesecond case, the entropies are trivially equal because the action is actually cocompact.
